# Generated by Django 3.1.1 on 2020-10-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200906_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
