# Generated by Django 3.1.1 on 2020-10-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
